name: flow_mujoco
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - ale-py==0.11.2
      - annotated-types==0.7.0
      - asttokens==3.0.0
      - attrs==25.3.0
      - beautifulsoup4==4.13.5
      - blinker==1.9.0
      - brax==0.13.0
      - bs4==0.0.2
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - chex==0.1.91
      - click==8.3.0
      - cloudpickle==3.1.1
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - dash==3.2.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - docstring-parser==0.17.0
      - etils==1.13.0
      - executing==2.2.1
      - farama-notifications==0.0.4
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - flask==3.1.2
      - flask-cors==6.0.1
      - flax==0.12.0
      # - flow-policy==0.0.0
      - fonttools==4.60.0
      - freetype-py==2.5.1
      - frozenlist==1.7.0
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glfw==2.10.0
      - grpcio==1.76.0
      - gymnasium==1.2.1
      - humanize==4.13.0
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - ipykernel==6.30.1
      - ipython==9.6.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - jax==0.7.2
      - jax-dataclasses==1.6.1
      - jaxlib==0.7.2
      - jaxopt==0.8.5
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - loader==2017.9.11
      - logbook==1.8.2
      - logcc==2018.3.1
      - lxml==6.0.2
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mediapy==1.2.4
      - meshio==5.3.5
      - ml-collections==1.1.0
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - msgpack==1.1.1
      - mujoco==3.3.6
      - mujoco-mjx==3.3.6
      - multidict==6.6.4
      - narwhals==2.6.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.5
      - numpy==2.2.6
      - open3d==0.19.0
      - opencv-python==4.12.0.88
      - opt-einsum==3.4.0
      - optax==0.2.6
      - orbax-checkpoint==0.11.25
      - packaging==25.0
      - pandas==2.3.2
      - parso==0.8.5
      - pendulum==3.1.0
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.4.0
      - playground==0.0.5
      - plotly==6.3.0
      - pony==0.7.19
      - prompt-toolkit==3.0.52
      - propcache==0.3.2
      - protobuf==6.32.1
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pygame==2.6.1
      - pyglet==2.1.9
      - pygments==2.19.2
      - pyopengl
      - pyparsing==3.2.5
      - pyquaternion==0.9.9
      - pyrender==0.1.45
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.36.2
      - requests==2.32.5
      - retrying==1.4.2
      - rich==14.1.0
      - rpds-py==0.27.1
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.16.2
      # - sdf==0.1
      - sentry-sdk==2.39.0
      - shtab==1.7.2
      - simplejson==3.20.2
      - six==1.17.0
      - smmap==5.0.2
      - soupsieve==2.8
      - stable-baselines3==2.7.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - tensorstore==0.1.77
      - termcc==2019.8.2
      - terminaltables==3.1.10
      - threadpoolctl==3.6.0
      - tifffile==2025.9.30
      - toolz==1.0.0
      - torch==2.8.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - treescope==0.1.10
      - trimesh==4.8.2
      # - triton==3.4.0
      - typeguard==4.4.4
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - tyro==0.9.26
      - tzdata==2025.2
      - urllib3==2.5.0
      - usd-core==25.8
      - wandb==0.21.0
      - wcwidth==0.2.14
      - websockets==15.0.1
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - wrap==2018.3.1
      - yarl==1.20.1
      - zipp==3.23.0


# name: myclone
# dependencies:
#   - _libgcc_mutex=0.1
#   - _openmp_mutex=5.1
#   - bzip2=1.0.8
#   - c-ares=1.34.5
#   - ca-certificates=2025.9.9
#   - cmake=3.14.0
#   - expat=2.7.1
#   - ld_impl_linux-64=2.40
#   - libcurl=8.15.0
#   - libev=4.33
#   - libffi=3.4.4
#   - libgcc-ng=11.2.0
#   - libgomp=11.2.0
#   - libnghttp2=1.57.0
#   - libssh2=1.11.1
#   - libstdcxx-ng=11.2.0
#   - libuuid=1.41.5
#   - libxcb=1.17.0
#   - libzlib=1.3.1
#   - lz4-c=1.9.4
#   - ncurses=6.5
#   - openssl=3.0.17
#   - pip=25.2
#   - pthread-stubs=0.3
#   - python=3.12.11
#   - readline=8.3
#   - rhash=1.4.3
#   - setuptools=78.1.1
#   - sqlite=3.50.2
#   - tk=8.6.15
#   - wheel=0.45.1
#   - xorg-libx11=1.8.12
#   - xorg-libxau=1.0.12
#   - xorg-libxdmcp=1.1.5
#   - xorg-xorgproto=2024.1
#   - xz=5.6.4
#   - zlib=1.3.1
#   - zstd=1.5.7
#   - pip:
#       - absl-py==2.3.1
#       - addict==2.4.0
#       - aiofiles==24.1.0
#       - aiohappyeyeballs==2.6.1
#       - aiohttp==3.12.15
#       - aiosignal==1.4.0
#       - ale-py==0.11.2
#       - annotated-types==0.7.0
#       - asttokens==3.0.0
#       - attrs==25.3.0
#       - beautifulsoup4==4.13.5
#       - blinker==1.9.0
#       - brax==0.13.0
#       - bs4==0.0.2
#       - certifi==2025.8.3
#       - charset-normalizer==3.4.3
#       - chex==0.1.91
#       - click==8.3.0
#       - cloudpickle==3.1.1
#       - comm==0.2.3
#       - configargparse==1.7.1
#       - contourpy==1.3.3
#       - cycler==0.12.1
#       - dash==3.2.0
#       - debugpy==1.8.17
#       - decorator==5.2.1
#       - docstring-parser==0.17.0
#       - etils==1.13.0
#       - executing==2.2.1
#       - farama-notifications==0.0.4
#       - fastjsonschema==2.21.2
#       - filelock==3.19.1
#       - flask==3.1.2
#       - flask-cors==6.0.1
#       - flax==0.12.0
#       # - flow-policy==0.0.0
#       - fonttools==4.60.0
#       - freetype-py==2.5.1
#       - frozenlist==1.7.0
#       - fsspec==2025.9.0
#       - gitdb==4.0.12
#       - gitpython==3.1.45
#       - glfw==2.10.0
#       - grpcio==1.76.0
#       - gymnasium==1.2.1
#       - humanize==4.13.0
#       - idna==3.10
#       - imageio==2.37.0
#       - importlib-metadata==8.7.0
#       - importlib-resources==6.5.2
#       - ipykernel==6.30.1
#       - ipython==9.6.0
#       - ipython-pygments-lexers==1.1.1
#       - ipywidgets==8.1.7
#       - itsdangerous==2.2.0
#       - jax==0.7.2
#       - jax-cuda12-pjrt==0.7.2
#       - jax-cuda12-plugin==0.7.2
#       - jax-dataclasses==1.6.1
#       - jaxlib==0.7.2
#       - jaxopt==0.8.5
#       - jedi==0.19.2
#       - jinja2==3.1.6
#       - joblib==1.5.2
#       - jsonschema==4.25.1
#       - jsonschema-specifications==2025.9.1
#       - jupyter-client==8.6.3
#       - jupyter-core==5.8.1
#       - jupyterlab-widgets==3.0.15
#       - kiwisolver==1.4.9
#       - lazy-loader==0.4
#       - loader==2017.9.11
#       - logbook==1.8.2
#       - logcc==2018.3.1
#       - lxml==6.0.2
#       - markdown==3.9
#       - markdown-it-py==4.0.0
#       - markupsafe==3.0.2
#       - matplotlib==3.9.2
#       - matplotlib-inline==0.1.7
#       - mdurl==0.1.2
#       - mediapy==1.2.4
#       - meshio==5.3.5
#       - ml-collections==1.1.0
#       - ml-dtypes==0.5.3
#       - mpmath==1.3.0
#       - msgpack==1.1.1
#       - mujoco==3.3.6
#       - mujoco-mjx==3.3.6
#       - multidict==6.6.4
#       - narwhals==2.6.0
#       - nbformat==5.10.4
#       - nest-asyncio==1.6.0
#       - networkx==3.5
#       - numpy==2.2.6
#       - nvidia-cublas-cu12==12.8.4.1
#       - nvidia-cuda-cupti-cu12==12.8.90
#       - nvidia-cuda-nvcc-cu12==12.9.86
#       - nvidia-cuda-nvrtc-cu12==12.8.93
#       - nvidia-cuda-runtime-cu12==12.8.90
#       - nvidia-cudnn-cu12==9.10.2.21
#       - nvidia-cufft-cu12==11.3.3.83
#       - nvidia-cufile-cu12==1.13.1.3
#       - nvidia-curand-cu12==10.3.9.90
#       - nvidia-cusolver-cu12==11.7.3.90
#       - nvidia-cusparse-cu12==12.5.8.93
#       - nvidia-cusparselt-cu12==0.7.1
#       - nvidia-nccl-cu12==2.27.3
#       - nvidia-nvjitlink-cu12==12.8.93
#       - nvidia-nvshmem-cu12==3.4.5
#       - nvidia-nvtx-cu12==12.8.90
#       - open3d==0.19.0
#       - opencv-python==4.12.0.88
#       - opt-einsum==3.4.0
#       - optax==0.2.6
#       - orbax-checkpoint==0.11.25
#       - packaging==25.0
#       - pandas==2.3.2
#       - parso==0.8.5
#       - pendulum==3.1.0
#       - pexpect==4.9.0
#       - pillow==11.3.0
#       - platformdirs==4.4.0
#       - playground==0.0.5
#       - plotly==6.3.0
#       - pony==0.7.19
#       - prompt-toolkit==3.0.52
#       - propcache==0.3.2
#       - protobuf==6.32.1
#       - psutil==7.1.0
#       - ptyprocess==0.7.0
#       - pure-eval==0.2.3
#       - pydantic==2.11.9
#       - pydantic-core==2.33.2
#       - pygame==2.6.1
#       - pyglet==2.1.9
#       - pygments==2.19.2
#       - pyopengl
#       - pyparsing==3.2.5
#       - pyquaternion==0.9.9
#       - pyrender==0.1.45
#       - python-dateutil==2.9.0.post0
#       - pytz==2025.2
#       - pyyaml==6.0.3
#       - pyzmq==27.1.0
#       - referencing==0.36.2
#       - requests==2.32.5
#       - retrying==1.4.2
#       - rich==14.1.0
#       - rpds-py==0.27.1
#       - scikit-image==0.25.2
#       - scikit-learn==1.7.2
#       - scipy==1.16.2
#       # - sdf==0.1
#       - sentry-sdk==2.39.0
#       - shtab==1.7.2
#       - simplejson==3.20.2
#       - six==1.17.0
#       - smmap==5.0.2
#       - soupsieve==2.8
#       - stable-baselines3==2.7.0
#       - stack-data==0.6.3
#       - sympy==1.14.0
#       - tensorboard==2.20.0
#       - tensorboard-data-server==0.7.2
#       - tensorboardx==2.6.4
#       - tensorstore==0.1.77
#       - termcc==2019.8.2
#       - terminaltables==3.1.10
#       - threadpoolctl==3.6.0
#       - tifffile==2025.9.30
#       - toolz==1.0.0
#       - torch==2.8.0
#       - tornado==6.5.2
#       - tqdm==4.67.1
#       - traitlets==5.14.3
#       - treescope==0.1.10
#       - trimesh==4.8.2
#       - triton==3.4.0
#       - typeguard==4.4.4
#       - typing-extensions==4.15.0
#       - typing-inspection==0.4.1
#       - tyro==0.9.26
#       - tzdata==2025.2
#       - urllib3==2.5.0
#       - usd-core==25.8
#       - wandb==0.21.0
#       - wcwidth==0.2.14
#       - websockets==15.0.1
#       - werkzeug==3.1.3
#       - widgetsnbextension==4.0.14
#       - wrap==2018.3.1
#       - yarl==1.20.1
#       - zipp==3.23.0
